// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp-Xnpy899c12sQzueVBYwqxnyyKD9iQs',
    appId: '1:1047978380452:android:abb8ffe20b78da0d0eaa31',
    messagingSenderId: '1047978380452',
    projectId: 'scs2025-a01f8',
    storageBucket: 'scs2025-a01f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSZfRCKtjh4R8BHy-zX0NS2PgJBnBp5ms',
    appId: '1:1047978380452:ios:e326e349805a3cc50eaa31',
    messagingSenderId: '1047978380452',
    projectId: 'scs2025-a01f8',
    storageBucket: 'scs2025-a01f8.firebasestorage.app',
    iosBundleId: 'com.example.saasIntro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSZfRCKtjh4R8BHy-zX0NS2PgJBnBp5ms',
    appId: '1:1047978380452:ios:e326e349805a3cc50eaa31',
    messagingSenderId: '1047978380452',
    projectId: 'scs2025-a01f8',
    storageBucket: 'scs2025-a01f8.firebasestorage.app',
    iosBundleId: 'com.example.saasIntro',
  );
}
